### PR TITLE
fix cannot sync trait without definitionRef

### LINKED ISSUE #998: trait capability without definitionRef cannot be synced locally
**Describe the bug**

`vela cap cent sync <center>` cannot sync trait capabilities that have no `definitionRef` into local.

**To Reproduce**

- remove local cap center(`https://github.com/oam-dev/catalog/tree/master/registry`) if added before 
- add cap center again `vela cap center config catalog https://github.com/oam-dev/catalog/tree/master/registry`
- sync cap `vela cap center sync catalog`
- list caps `vela cap ls`

Then we will noticed that several trait capabilities are missed, e.g., ingress

**Reason**

`vela cap center sync` will use the CRD name of cap as file name saved locally. But currently, it's allowed for trait to omit definitionRef field, namely, it will omit CRD name because CRD name is `definitionRef.name` So vela cannot save it into local correctly.

### PR DESCRIPTION
**Pull request by captainroy-hy**
to fix #998 
solution: use trait cap name instead of trait's CRD name as file name saved locally

because unit tests in pkg `capability` are skipped by CI, I just run those tests locally.

Signed-off-by: roy wang <seiwy2010@gmail.com>

### CODE REVIEW

File: pkg/serverlib/capability.go [hunk 1]
```diff
@@ -119,7 +119,7 @@ func InstallCapability(client client.Client, mapper discoverymapper.DiscoveryMap
 		}
 	case types.TypeTrait:
 		var td v1alpha2.TraitDefinition
-		traitdata, err := ioutil.ReadFile(filepath.Clean(filepath.Join(repoDir, tp.CrdName+".yaml")))
+		traitdata, err := ioutil.ReadFile(filepath.Clean(filepath.Join(repoDir, tp.Name+".yaml")))
```
Comment (wonderflow) [inline pkg/serverlib/capability.go:122]: what about the workload in L94

Comment (captainroy-hy) [reply pkg/serverlib/capability.go:122]: I keep all code related to workload unchanged. So workloadDef file is still stored as CRD name as well as read.

**Review by wonderflow — APPROVED** [review]
LGTM
