### PR TITLE
Fix: vela-cli does not print cluster name, if application installed i…

### LINKED ISSUE #3690: vela-cli does not print cluster name, if application installed in default cluster
**Describe the bug**

**To Reproduce**

1. follow official online doc to install kubevela and velaux
```
➜  local vela addon enable velaux serviceType=NodePort --version v1.3.1
# ignore something here
Please access the velaux from the following endpoints:
+---------+-----------+----------------------------+---------------------------+
| CLUSTER | COMPONENT |  REF(KIND/NAMESPACE/NAME)  |         ENDPOINT          |
+---------+-----------+----------------------------+---------------------------+
|         | velaux    | Service/vela-system/velaux | http://192.168.65.4:30150 |
+---------+-----------+----------------------------+---------------------------+
```

2. check  Applicaiton's status

```
➜  KubeVela vela -n vela-system status addon-velaux --endpoint=true
+---------+-----------+----------------------------+---------------------------+
| CLUSTER | COMPONENT |  REF(KIND/NAMESPACE/NAME)  |         ENDPOINT          |
+---------+-----------+----------------------------+---------------------------+
|         | velaux    | Service/vela-system/velaux | http://192.168.65.4:30989 |
+---------+-----------+----------------------------+---------------------------+
```

3. check addon's status

```
➜  KubeVela vela addon status velaux
addon velaux status is enabled
installedVersion: v1.3.0
installedClusters: [local]
```

4. both post message of "vela addon enable" and output of "vela status" do not print cluster name.

**Expected behavior**
1. 'vela addon enable' and  'vela status' can print cluster name, as what `vela addon status` did.

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

### PR DESCRIPTION
**Pull request by StevenLeiZhang**
Fix vela-cli does not print cluster name, if application installed in default cluster

Signed-off-by: StevenLeiZhang <zhangleiic@163.com>

### Description of your changes

Fixes #3690 

How to fix it?
1. show default name of cluster as what `vela addon status` did

```
➜  bin git:(fix-clus) ✗  ./vela addon enable velaux --version=v1.3.1   serviceType=NodePort

#ignore something here
Please access the velaux from the following endpoints:
+---------+-----------+----------------------------+---------------------------+
| CLUSTER | COMPONENT |  REF(KIND/NAMESPACE/NAME)  |         ENDPOINT          |
+---------+-----------+----------------------------+---------------------------+
| local   | velaux    | Service/vela-system/velaux | http://192.168.65.4:30256 |
+---------+-----------+----------------------------+---------------------------+
To check the initialized admin user name and password by:
    vela logs -n vela-system --name apiserver addon-velaux | grep "initialized admin username"
To open the dashboard directly by port-forward:
    vela port-forward -n vela-system addon-velaux 9082:80
Select "Cluster: local | Namespace: vela-system | Component: velaux | Kind: Service" from the prompt.
Please refer to https://kubevela.io/docs/reference/addons/velaux for more VelaUX addon installation and visiting method.


```

```
➜  bin git:(fix-clus) ✗  ./vela -n vela-system status addon-velaux --endpoint=true
+---------+-----------+----------------------------+---------------------------+
| CLUSTER | COMPONENT |  REF(KIND/NAMESPACE/NAME)  |         ENDPOINT          |
+---------+-----------+----------------------------+---------------------------+
| local   | velaux    | Service/vela-system/velaux | http://192.168.65.4:30256 |
+---------+-----------+----------------------------+---------------------------+

```

```
➜  bin git:(fix-clus) ✗ ./vela addon status  velaux
addon velaux status is enabled 
installedVersion: v1.3.1 
installedClusters: [local] 

```

2. reuse code
since [func printAppEndpoints(ctx context.Context, client client.Client, appName string, namespace string, f Filter, velaC common.Args)](https://github.com/oam-dev/kubevela/blob/eb60d94a0638ed9132b1c4590f255d6fe00a4c19/references/cli/status.go#L166) already exists, just reuse it to avoid duplicate code

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

File: references/cli/addon.go [hunk 1]
```diff
@@ -193,16 +191,10 @@ Enable addon for specific clusters, (local means control plane):
...
 func AdditionalEndpointPrinter(ctx context.Context, c common.Args, k8sClient client.Client, name string) {
-	endpoints, _ := GetServiceEndpoints(ctx, k8sClient, pkgaddon.Convert2AppName(name), types.DefaultKubeVelaNS, c, Filter{})
-	if len(endpoints) > 0 {
-		table := tablewriter.NewWriter(os.Stdout)
-		table.SetColWidth(100)
-		table.SetHeader([]string{"Cluster", "Component", "Ref(Kind/Namespace/Name)", "Endpoint"})
-		for _, endpoint := range endpoints {
-			table.Append([]string{endpoint.Cluster, endpoint.Component, fmt.Sprintf("%s/%s/%s", endpoint.Ref.Kind, endpoint.Ref.Namespace, endpoint.Ref.Name), endpoint.String()})
-		}
-		fmt.Printf("Please access the %s from the following endpoints:\n", name)
```
Comment (wonderflow) [inline references/cli/addon.go:204]: we can keep this line in the function `printAppEndpoints`

**Review by wonderflow — APPROVED** [review]
good catch , thanks

LGTM after nits

**Review by barnettZQG — APPROVED** [review]
lgtm

**Review by Somefive — APPROVED** [review]

File: references/cli/addon.go (hunk 1 above)
Comment (StevenLeiZhang) [reply references/cli/addon.go:204]: ‘fmt.Printf("Please access the %s from the following endpoints:\n", name)’ this line locate at `AdditionalEndpointPrinter` not `printAppEndpoints` before my refactor. This commit just reuse `printAppEndpoints`, and does not change any code of it.

Do you think we could move this line to `printAppEndpoints`? it will make `./vela -n vela-system status addon-velaux --endpoint=true` to print this message.

Comment (wonderflow) [reply references/cli/addon.go:204]: yes, I think we should add that.

```
$ ./vela -n vela-system status addon-velaux --endpoint=true
Please access the velaux from the following endpoints:
+---------+-----------+----------------------------+---------------------------+
| CLUSTER | COMPONENT |  REF(KIND/NAMESPACE/NAME)  |         ENDPOINT          |
+---------+-----------+----------------------------+---------------------------+
| local   | velaux    | Service/vela-system/velaux | http://192.168.65.4:30256 |
+---------+-----------+----------------------------+---------------------------+
```

It looks better.

Comment (StevenLeiZhang) [reply references/cli/addon.go:204]: > yes, I think we should add that.
> 
> ```
> $ ./vela -n vela-system status addon-velaux --endpoint=true
> Please access the velaux from the following endpoints:
> +---------+-----------+----------------------------+---------------------------+
> | CLUSTER | COMPONENT |  REF(KIND/NAMESPACE/NAME)  |         ENDPOINT          |
> +---------+-----------+----------------------------+---------------------------+
> | local   | velaux    | Service/vela-system/velaux | http://192.168.65.4:30256 |
> +---------+-----------+----------------------------+---------------------------+
> ```
> 
> It looks better.

please note this line https://github.com/StevenLeiZhang/kubevela/blob/62c3e7ee4334b84d3c113e2b2ff784cacd1f88ce/references/cli/addon.go#L195

Comment (wonderflow) [reply references/cli/addon.go:204]: I think this is fine, we are using `addon-velaux` in command:

```
vela -n vela-system status addon-velaux --endpoint=true
```

Comment (StevenLeiZhang) [reply references/cli/addon.go:204]: > I think this is fine, we are using `addon-velaux` in command:
> 
> ```
> vela -n vela-system status addon-velaux --endpoint=true
> ```

It will always print "addon-velaux". It is ok for `vela -n vela-system status addon-velaux `, but may let user feel confused for `vela addon enable velaux`

Comment (wonderflow) [reply references/cli/addon.go:204]: We can use this label to check and get the name `addons.oam.dev/name`
