### PR TITLE
Fix: verify password valid

### LINKED ISSUE #3613: 初始化生成的用户密码可能不符合velaux的表单校验的要求
问题描述：用户管理接口初始化时生成的密码随机字符串可能会生成全是字母/数字的字符串，而velaux前端的表单的校验要求输入的字符串至少一个数字和字母。

密码字符串生成函数如下：
```
package utils

import (
	"math/rand"
	"time"
)

var letters = []rune("abcdefghijklmnopqrstuvwxyz123456789")

// RandomString generate random string.
func RandomString(n int) string {
	randSrc := rand.NewSource(time.Now().UnixNano())
	b := make([]rune, n)
	for i := range b {
		b[i] = letters[randSrc.Int63()%int64(len(letters))]
	}
	return string(b)
}
```

velaux的登录表单中密码的校验规则为“密码必须包含至少一个数字和字母，长度在8-16位之间”，匹配如下：
```
export const checkUserPassword = /^(?=.*[0-9])(?=.*[a-zA-Z])([a-zA-Z0-9]{8,16})$/;
```

另外，Login按钮的中文应该是登录而不是登陆。

### PR DESCRIPTION
**Pull request by zhiyuone**
Signed-off-by: Zhiyu Wang <zhiyuwang.newbis@gmail.com>

`utils2.RandomString` may generate plain string without number

### Description of your changes

Fixes #3613

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

File: pkg/apiserver/rest/usecase/user.go [hunk 1]
```diff
@@ -231,6 +250,9 @@ func (u *userUsecaseImpl) UpdateUser(ctx context.Context, user *model.User, req
 		user.Alias = req.Alias
 	}
 	if req.Password != "" {
+		if !validPassword(req.Password) {
```
Comment (barnettZQG) [inline pkg/apiserver/rest/usecase/user.go:253]: The password will be validated in the webservice handle function.

File: pkg/apiserver/rest/usecase/user.go [hunk 2]
```diff
@@ -82,7 +84,15 @@ func (u *userUsecaseImpl) Init(ctx context.Context) error {
 		Name: admin,
 	}); err != nil {
 		if errors.Is(err, datastore.ErrRecordNotExist) {
-			pwd := utils2.RandomString(8)
+			pwd := func() string {
```
Comment (FogDong) [inline pkg/apiserver/rest/usecase/user.go:87]: I think it's better if we make it a standalone function.

**Review by barnettZQG — APPROVED** [review]
