### PR TITLE
fix generate schema for helm values

### LINKED ISSUE #1369: helm chart ComponentDefinition doesn't generate jsonschema ConfigMap
**Cluster information**
- k8s v1.19.1 [kind]

ComponentDefinition

```yaml
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: elasticsearch-chart
  annotations:
    definition.oam.dev/description: helm chart for elasticsearch
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: StatefulSet
  schematic:
    helm:
      release:
        chart:
          spec:
            chart: "elasticsearch"
            version: "7.11.1"
      repository:
        url: "https://helm.elastic.co/"
```

Describe

```shell
$ k describe componentdefinitions.core.oam.dev elasticsearch-chart
Name:         elasticsearch-chart
Namespace:    default
Labels:       <none>
Annotations:  definition.oam.dev/description: helm chart for elasticsearch
API Version:  core.oam.dev/v1beta1
Kind:         ComponentDefinition
Metadata:
  Creation Timestamp:  2021-03-31T02:11:32Z
  Generation:          1
  Managed Fields:
    API Version:  core.oam.dev/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:definition.oam.dev/description:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:schematic:
          .:
          f:helm:
            .:
            f:release:
              .:
              f:chart:
            f:repository:
              .:
              f:url:
        f:workload:
          .:
          f:definition:
            .:
            f:apiVersion:
            f:kind:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2021-03-31T02:11:32Z
    API Version:  core.oam.dev/v1alpha2
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
    Manager:         dbe798eb-1b97-45fe-86ce-a6b6b8543a14
    Operation:       Update
    Time:            2021-03-31T02:11:33Z
  Resource Version:  2093783
  Self Link:         /apis/core.oam.dev/v1beta1/namespaces/default/componentdefinitions/elasticsearch-chart
  UID:               dbe798eb-1b97-45fe-86ce-a6b6b8543a14
Spec:
  Schematic:
    Helm:
      Release:
        Chart:
          Spec:
            Chart:    elasticsearch
            Version:  7.11.1
      Repository:
        URL:  https://helm.elastic.co/
  Workload:
    Definition:
      API Version:  apps/v1
      Kind:         StatefulSet
Status:
  Conditions:
    Last Transition Time:  2021-03-31T02:11:33Z
    Message:               cannot store capability elasticsearch-chart in ConfigMap: failed to generate OpenAPI v3 JSON schema for capability elasticsearch-chart: cannot generate schema from Values file: cannot load schema by SwaggerLoader: error unmarshaling JSON: Error while unmarshalling property 'components' (*openapi3.Components): Error while unmarshalling property 'schemas' (*openapi3.Schemas): Error while unmarshalling property 'properties' (*openapi3.Schemas): Error while unmarshalling property 'properties' (*openapi3.Schemas): Error while unmarshalling property 'items' (*openapi3.SchemaRef): Error while unmarshalling property 'properties' (*openapi3.Schemas): Error while unmarshalling property 'items' (*openapi3.SchemaRef): Failed to unmarshal extension properties: json: cannot unmarshal array into Go value of type map[string]json.RawMessage
Input: [{"properties":{"path":{"enum":["/"],"type":"string"}},"required":["path"],"type":"object"}]
    Reason:  ReconcileError
    Status:  False
    Type:    Synced
Events:
  Type     Reason                                Age              From                 Message
  ----     ------                                ----             ----                 -------
  Warning  cannot store capability in ConfigMap  4s (x2 over 5s)  ComponentDefinition  failed to generate OpenAPI v3 JSON schema for capability elasticsearch-chart: cannot generate schema from Values file: cannot load schema by SwaggerLoader: error unmarshaling JSON: Error while unmarshalling property 'components' (*openapi3.Components): Error while unmarshalling property 'schemas' (*openapi3.Schemas): Error while unmarshalling property 'properties' (*openapi3.Schemas): Error while unmarshalling property 'properties' (*openapi3.Schemas): Error while unmarshalling property 'items' (*openapi3.SchemaRef): Error while unmarshalling property 'properties' (*openapi3.Schemas): Error while unmarshalling property 'items' (*openapi3.SchemaRef): Failed to unmarshal extension properties: json: cannot unmarshal array into Go value of type map[string]json.RawMessage
Input: [{"properties":{"path":{"enum":["/"],"type":"string"}},"required":["path"],"type":"object"}]
```

### PR DESCRIPTION
**Pull request by captainroy-hy**
to fix #1369 
### Bug reason:
The values file contains such a snippet that, an array type property embedss an array type property in its items list.

```yaml
...
  hosts:
    - host: chart-example.local
      paths:
        - path: /
...
```

Signed-off-by: roy wang <seiwy2010@gmail.com>

### CODE REVIEW

File: pkg/appfile/helm/schema.go [hunk 1]
```diff
@@ -209,6 +209,7 @@ func handleItemsOfArrayType(t map[string]interface{}) {
 	if t["type"] == "array" {
 		if i, ok := t["items"].([]interface{}); ok {
 			itemSpec, _ := i[0].(map[string]interface{})
```
Comment (wonderflow) [inline pkg/appfile/helm/schema.go:211]: 1. The array could be empty, check the length first.

2. The convert can be different types, you should write a switch for it.
  ```
  switch i[0].(type){
   case map[string]interface{}: 
   case []interface{}:
   defaut:  // other types..
   ...
  }
  ```

**Review by wonderflow — APPROVED** [review]
LGTM
