### PR TITLE
fix "cap show"  cannot print  keyValue type bug

### LINKED ISSUE #984: "vela show" does't generate complete cli reference for trait "env"
Applying TraitDefinition `env` https://github.com/oam-dev/catalog/blob/master/registry/podenv.yaml, run `vela show env` and it didn't generate list type env parameter.

image

/cc @wonderflow

### PR DESCRIPTION
**Pull request by WangYikewyk**
fix #984 
Before:
% vela show env
Properties
+------+-------------+-------------+----------+---------+
| NAME | DESCRIPTION |    TYPE     | REQUIRED | DEFAULT |
+------+-------------+-------------+----------+---------+
| env  |             | [env](#env) | true     |         |
+------+-------------+-------------+----------+---------+

env
+------+-------------+------+----------+---------+
| NAME | DESCRIPTION | TYPE | REQUIRED | DEFAULT |
+------+-------------+------+----------+---------+
+------+-------------+------+----------+---------+

After:
Properties
+------+-------------+-------------------+----------+---------+
| NAME | DESCRIPTION |       TYPE        | REQUIRED | DEFAULT |
+------+-------------+-------------------+----------+---------+
| env  |             | map[string]string | true     |         |
+------+-------------+-------------------+----------+---------+

### CODE REVIEW

File: pkg/plugins/references.go [hunk 1]
```diff
@@ -315,9 +315,13 @@ func (ref *ParseReference) parseParameters(paraValue cue.Value, paramKey string,
...
 				depth := *recurseDepth
-				// TODO(zzxwill) this case not processed  `selector?: [string]: string`
-				if name == "selector" {
-					param.PrintableType = "map[string]string"
+				if subField, _ := val.Struct(); subField.Len() == 0 { // err cannot be not nil,so ignore it
+					if mapValue, ok := val.Elem(); ok {
+						// In the future we could recursive call to surpport complex map-value(struct or list)
+						param.PrintableType = fmt.Sprintf("map[string]%s", mapValue.IncompleteKind().String())
+					} else {
+						return fmt.Errorf("failed to got mapValue kind from %s", param.Name)
```
Comment (zzxwill) [inline pkg/plugins/references.go:323]:
```suggestion
						return fmt.Errorf("failed to got map kind from %s", param.Name)
```

**Review by wonderflow — APPROVED** [review]
