### PR TITLE
Fix: health check will check for multiclusters

### LINKED ISSUE #2607: [Bug] The health check in workflow does not support multi cluster
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

**Cluster information**

**Additional context**

### PR DESCRIPTION
**Pull request by wonderflow**
### Description of your changes

Fixes #2607

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Review by FogDong — APPROVED** [review]

**Comment by FogDong** [comment]
Fix #2607

**Review by Somefive — APPROVED** [review]

**Review by hongchaodeng — APPROVED** [review]

File: pkg/cue/process/handle.go [hunk 1]
```diff
@@ -292,6 +293,13 @@ func (ctx *templateContext) GetCtx() context.Context {
 	return context.TODO()
 }
 
+func (ctx *templateContext) SetCtx(newContext context.Context) {
```
Comment (hongchaodeng) [inline pkg/cue/process/handle.go:296]: SetCtxIfNotExist

**Review by zzxwill — APPROVED** [review]
