### PR TITLE
Fix: add terraform aws provider without AWS_SESSION_TOKEN

### LINKED ISSUE #3589: Failed to add terraform-aws provider. Error: must specify a value for AWS_SESSION_TOKEN
**Describe the bug**

Failed to add terraform-aws provider. 

```
➜  addons git:(terraform) ✗ vela provider add terraform-aws --AWS_ACCESS_KEY_ID=xxx --AWS_SECRET_ACCESS_KEY=yyy --AWS_DEFAULT_REGION=us-east-1
Error: must specify a value for AWS_SESSION_TOKEN
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**KubeVela Version**

1.3.0

**Cluster information**

**Additional context**

### PR DESCRIPTION
**Pull request by zzxwill**
Fix #3589 and refine prompts for cli

Signed-off-by: Zheng Xi Zhou <zzxwill@gmail.com>

### Description of your changes

Fixes #

I have:

- [ ] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary. 
- [ ] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

File: references/cli/provider.go [hunk 1]
```diff
@@ -276,7 +277,7 @@ func listProviders(ctx context.Context, k8sClient client.Client) error {
 	defs, err := getTerraformProviderTypes(ctx, k8sClient)
 	if err != nil {
 		if kerrors.IsNotFound(err) {
-			return errors.New("no Terraform Cloud Provider found, please run `vela addon enable` first")
+			fmt.Println("no Terraform Cloud Provider found, please run `vela addon enable` first")
```
Comment (Somefive) [inline references/cli/provider.go:280]: It might be better to pass a io.Writer inside instead of directly using fmt.

**Review by Somefive — APPROVED** [review]
Generally LGTM.
