### PR TITLE
Fix `vela ls` issue

### LINKED ISSUE #534: [BUG] all svc including those deployed without `--staging` flag will appear to be `staging` status
All svc including those deployed without `--staging` flag will appear to be `staging` status in cmd `vela ls
```
vela ls
SERVICE	APP	TYPE      	TRAITS	STATUS 	CREATED-TIME
s1     	a1 	webservice	      	Staging	2020-11-07 21:29:01 +0800 CST
s2     	a2 	webservice	      	Staging	2020-11-07 22:01:00 +0800 CST
s3     	a3 	          	      	Staging	2020-11-07 23:39:20.090882 +0800 CST
```

### PR DESCRIPTION
**Pull request by zzxwill**
By default, all svc deployed without `--staging` will appear
to be `staging` in cmd `vela ls`.
To fix #534

### CODE REVIEW

File: pkg/commands/ls.go [hunk 1]
```diff
@@ -113,7 +113,14 @@ func mergeStagingComponents(deployed []apis.ComponentMeta, env *types.EnvMeta, i
 					v.Traits[j] = t
 				}
 				aspec.Components[i] = v
+				/* Before any traits is attached to the workload, if ApplicationConfiguration is retrieved through
+				OpenAPI, the .spec.Components[].Traits is nil; if it's resembled by local file, .spec.Components[].Traits
+				is the []v1alpha2.ComponentTrait, 0). Let's set it to be equal before comparing the whole .Spec field.*/
+				if compMeta.AppConfig.Spec.Components[i].Traits == nil && len(v.Traits) == 0 {
+					compMeta.AppConfig.Spec.Components[i].Traits = aspec.Components[i].Traits
+				}
```
Comment (zzxwill) [inline pkg/commands/ls.go:121]: I am afraid the hack way here might not be the best solution. One solution is to change the response of client-go from `ApplicationConfiguration` to make `.spec.Components[].Traits` to be in Golang slice, the other way is to change the type of traits of https://github.com/oam-dev/kubevela/blob/master/pkg/appfile/service.go#L114 which I think the type is reasonable. 
```
traits := make([]v1alpha2.ComponentTrait, 0)
```
I could not find a way out of the dilemma, so here is a solution to the issue #534

**Comment by hongchaodeng** [comment]
@zzxwill 
Can you provide an analysis of the root cause of the issue?

File: pkg/commands/ls.go [hunk 2]
```diff
@@ -113,7 +113,14 @@ func mergeStagingComponents(deployed []apis.ComponentMeta, env *types.EnvMeta, i
 					v.Traits[j] = t
 				}
 				aspec.Components[i] = v
+				/* Before any traits is attached to the workload, if ApplicationConfiguration is retrieved through
```
Comment (hongchaodeng) [inline pkg/commands/ls.go:116]: Why is it retrieved from OpenAPI?

File: pkg/commands/ls.go [hunk 3]
```diff
@@ -113,7 +113,14 @@ func mergeStagingComponents(deployed []apis.ComponentMeta, env *types.EnvMeta, i
...
+				OpenAPI, the .spec.Components[].Traits is nil; if it's resembled by local file, .spec.Components[].Traits
```
Comment (hongchaodeng) [inline pkg/commands/ls.go:117]: What do you mean by "resembled by local file"?

File: pkg/commands/ls.go [hunk 4]
```diff
@@ -113,7 +113,14 @@ func mergeStagingComponents(deployed []apis.ComponentMeta, env *types.EnvMeta, i
...
+				is the []v1alpha2.ComponentTrait, 0). Let's set it to be equal before comparing the whole .Spec field.*/
```
Comment (hongchaodeng) [inline pkg/commands/ls.go:118]: > is the []v1alpha2.ComponentTrait, 0)

What does this mean?

File: pkg/commands/ls.go [hunk 5]
```diff
@@ -113,7 +113,14 @@ func mergeStagingComponents(deployed []apis.ComponentMeta, env *types.EnvMeta, i
...
+				if compMeta.AppConfig.Spec.Components[i].Traits == nil && len(v.Traits) == 0 {
```
Comment (hongchaodeng) [inline pkg/commands/ls.go:119]: Change to following:

```Go
if  len(compMeta.AppConfig.Spec.Components[i].Traits) == 0 {
  compMeta.AppConfig.Spec.Components[i].Traits = nil
}
if len(v.Traits) == 0 {
  v.Traits = nil
}
```

File: pkg/commands/ls.go (hunk 2 above)
Comment (zzxwill) [reply pkg/commands/ls.go:116]: It's retrieved as below https://github.com/oam-dev/kubevela/blob/master/pkg/oam/application.go#L91-L95.
```
var appConfig corev1alpha2.ApplicationConfiguration
		if err := c.Get(ctx, client.ObjectKey{Name: opt.AppName, Namespace: opt.Namespace}, &appConfig); err != nil {
			return appConfigList, err
		}
```

File: pkg/commands/ls.go (hunk 3 above)
Comment (zzxwill) [reply pkg/commands/ls.go:117]: We are comparing appConfig with the one from cached in local file to check whether the status of the application is staging. For details, please refer to https://github.com/oam-dev/kubevela/blob/master/pkg/appfile/service.go#L73.

File: pkg/commands/ls.go (hunk 4 above)
Comment (zzxwill) [reply pkg/commands/ls.go:118]: It should be `make([]v1alpha2.ComponentTrait, 0)`:)

File: pkg/commands/ls.go (hunk 5 above)
Comment (zzxwill) [reply pkg/commands/ls.go:119]: I intended to check both  `compMeta.AppConfig.Spec.Components[i].Traits == nil` and `len(v.Traits) == 0`. If only one is `nil` or `make([]v1alpha2.ComponentTrait, 0`, we don't want to do anything. And they are different which means the status of the application should be `staging`.

is it better?
```
if compMeta.AppConfig.Spec.Components[i].Traits == nil && len(v.Traits) == 0 {
					aspec.Components[i].Traits = nil
				}
```

**Review by wonderflow — APPROVED** [review]
