### PR TITLE
fix make core-run panic

### LINKED ISSUE #361: [BUG] failed to run "go run cmd/core/main.go"
**Describe the bug**

```
➜  /Users/zhouzhengxi/Programming/golang/src/github.com/oam-dev/kubevela git:(master) k get configmaps
NAME          DATA   AGE
vela-config   2      34s
➜  /Users/zhouzhengxi/Programming/golang/src/github.com/oam-dev/kubevela git:(master) go run cmd/core/main.go
2020-10-08T21:52:52.357+0800	ERROR	vela-runtime	unable to install the dependency	{"error": "configmaps \"vela-config\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
	/Users/zhouzhengxi/Programming/golang/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
main.main
	/Users/zhouzhengxi/Programming/golang/src/github.com/oam-dev/kubevela/cmd/core/main.go:97
runtime.main
	/usr/local/go/src/runtime/proc.go:203
exit status 1
```
**To Reproduce**

- Get latest code from `git@github.com:oam-dev/kubevela.git`
commit: aa9c96d0b5ac6f332e3cb94948fc2082d425df77

- Run `go run cmd/core/main.go`.

**Expected behavior**

**Screenshots**

**Cluster information**

**Additional context**

### PR DESCRIPTION
**Pull request by wonderflow**
fixes #361

### CODE REVIEW

File: pkg/controller/dependency/install.go [hunk 1]
```diff
@@ -55,6 +55,9 @@ func Install(client client.Client) error {
 	velaConfigNN := k8stypes.NamespacedName{Name: VelaConfigName, Namespace: types.DefaultOAMNS}
 	velaConfig := v1.ConfigMap{}
 	if err := client.Get(context.TODO(), velaConfigNN, &velaConfig); err != nil {
+		if apierrors.IsNotFound(err) {
+			return nil
```
Comment (ryanzhang-oss) [inline pkg/controller/dependency/install.go:59]: add a log?

**Review by ryanzhang-oss — APPROVED** [review]

File: pkg/controller/dependency/install.go (hunk 1 above)
Comment (wonderflow) [reply pkg/controller/dependency/install.go:59]: Not need, this could be very normal case
