### PR TITLE
fix vela traits not compatible with installed capability

### LINKED ISSUE #1029: "vela traits" will make  installed traits become “uninstalled”
I‘m not sure whether this is a bug.  After run "vela traits" my  installed capabilities become “uninstalled”
vela version:0.3.2
kubernetes cluster version:1.19.1
image
It's seem to be "vela traits" refresh local trait info, and make source info lost.
Before:
image
After:
image

### PR DESCRIPTION
**Pull request by WangYikewyk**
fix #1029
fix issue  [1029](https://github.com/oam-dev/kubevela/issues/1029)
 add source info into workload/trait definition's **extension** field

### CODE REVIEW

File: pkg/serverlib/capability.go [hunk 1]
```diff
@@ -421,3 +430,18 @@ func checkInstallStatus(repoName string, tmp types.Capability) string {
 	}
 	return status
 }
+
+func addSourceIntoExtension(in *runtime.RawExtension, source *types.Source) error {
```
Comment (wonderflow) [inline pkg/serverlib/capability.go:434]: please add test for it

**Review by wonderflow — APPROVED** [review]
